config/routes.rb
MealMate::Application.routes.draw do

  devise_for :users
  root :to => "home#index"

  resources :plans do
    resources :meals do
      resources :options do
        resources :foods
      end
    end
  end
  

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :option
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
  end

  def show
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end

    @food = Food.find(food_id)
  end

  def new
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
    @food = Food.new 
  end

  def edit
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end

    @food = Food.find(food_id)
  end

  def create
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @food = @user.plans.find(plan_id).meals.find(meal_id).options.find(option_id).foods.create(food_params)

    if @food.save
      flash[:notice] = "Successfully created new food"
      redirect_to plan_path(@food.option.meal.plan)
    else
      flash[:notice] = "Error in creating new food"
      render :action => 'new'
    end
  end

  def update
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @food = Food.find(food_id)
    @food.update(food_params)
  
    if @food.save
      flash[:notice] = "Successfully updated food"
      redirect_to plan_meal_option_food_path(@food.option.meal.plan, @food.option.meal, @food.option, @food)
    else
      flash[:notice] = "Error in updating food"
      render :action => 'new'
    end
  end

  def destroy
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @food = Food.find(food_id)
    @option = @food.option
  
    if @food.destroy
      flash[:notice] = "Successfully deleted food"
      redirect_to plan_meal_option_path(@option.meal.plan, @option.meal, @option)
    else
      flash[:notice] = "Error in deleteing food"
      render :action => 'new'
    end
  end

  private
    def food_params
      params.require(:food).permit(:title, :description, :calories, :protien, :fat, :transfat, :monofat, :polyfat, :carbs, :suger, :fiber)
    end

    def food_id
      params.require(:id)
    end

    def plan_id
      params.require(:plan_id)
    end

    def meal_id
      params.require(:meal_id)
    end

    def option_id
      params.require(:option_id)
    end

end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= form_for @food, url: plan_meal_option_food_path do |f| %>

  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/><br/>

  <%= f.label :description %><br/>
  <%= f.text_field :description %><br/><br/>

  <%= f.label :calories %><br/>
  <%= f.text_field :calories %><br/><br/>

  <%= f.label :protien %><br/>
  <%= f.text_field :protien %><br/><br/>

  <%= f.label :fat %><br/>
  <%= f.text_field :fat %><br/><br/>

  <%= f.label :transfat %><br/>
  <%= f.text_field :transfat %><br/><br/>

  <%= f.label :monofat %><br/>
  <%= f.text_field :monofat %><br/><br/>

  <%= f.label :polyfat %><br/>
  <%= f.text_field :polyfat %><br/><br/>

  <%= f.label :carbs %><br/>
  <%= f.text_field :carbs %><br/><br/>

  <%= f.label :suger %><br/>
  <%= f.text_field :suger %><br/><br/>

  <%= f.label :fiber %><br/>
  <%= f.text_field :fiber %><br/><br/>

  <%= f.hidden_field :_destroy %>

  <%= f.submit %>

<% end %>

app/views/foods/new.html.erb
<h1>Edit Food</h1>

<%= form_for @food, url: plan_meal_option_foods_path do |f| %>

  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/><br/>

  <%= f.label :description %><br/>
  <%= f.text_field :description %><br/><br/>

  <%= f.label :calories %><br/>
  <%= f.text_field :calories %><br/><br/>

  <%= f.label :protien %><br/>
  <%= f.text_field :protien %><br/><br/>

  <%= f.label :fat %><br/>
  <%= f.text_field :fat %><br/><br/>

  <%= f.label :transfat %><br/>
  <%= f.text_field :transfat %><br/><br/>

  <%= f.label :monofat %><br/>
  <%= f.text_field :monofat %><br/><br/>

  <%= f.label :polyfat %><br/>
  <%= f.text_field :polyfat %><br/><br/>

  <%= f.label :carbs %><br/>
  <%= f.text_field :carbs %><br/><br/>

  <%= f.label :suger %><br/>
  <%= f.text_field :suger %><br/><br/>

  <%= f.label :fiber %><br/>
  <%= f.text_field :fiber %><br/><br/>

  <%= f.hidden_field :_destroy %>

  <%= f.submit %>

<% end %>

app/views/foods/show.html.erb
<br/><br/> 
<%= link_to "View", plan_meal_option_food_path(@food.option.meal.plan, @food.option.meal, @food.option, @food), :method => :get %> |
<%= link_to "Edit", edit_plan_meal_option_food_path(@food.option.meal.plan, @food.option.meal, @food.option, @food), :method => :get %> |
<%= link_to "Delete", plan_meal_option_food_path(@food.option.meal.plan, @food.option.meal, @food.option, @food), :method => :delete %>
<br/><br/> 
<%= @food.title %>: <%= @food.description %><br/>
<br/><br/> 
calories: <%= @food.calories %><br/>
protien: <%= @food.protien %><br/>
fat: <%= @food.fat %><br/>
transfat: <%= @food.transfat %><br/>
monofat: <%= @food.monofat %><br/>
polyfat: <%= @food.polyfat %><br/>
carbs: <%= @food.carbs %><br/>
suger: <%= @food.suger %><br/>
fiber: <%= @food.fiber %><br/>