config/routes.rb
MealMate::Application.routes.draw do

  devise_for :users
  root :to => "home#index"

  resources :plans do
    resources :meals do
      resources :options do
        resources :foods
      end
    end
  end
  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  has_many :meals
  accepts_nested_attributes_for :meals#, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  end

  def show
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
    @plan = Plan.find(plan_id)
  end

  def new
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @plan = Plan.new
    4.times do
      plan = @plan.meals.build
      4.times do
        option = plan.options.build
        option.foods.build
      end
    end
  end

  def edit
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end

    @plan = Plan.find(plan_id)
  end

  def create
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @plan = @user.plans.create(plan_params)
  
    if @plan.save
      flash[:notice] = "Successfully created new plan"
      redirect_to plan_path(@plan)
    else
      flash[:notice] = "Error in creating new plan"
      render :action => 'new'
    end
  end

  def update
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @plan = Plan.find(plan_id)
    @plan.update(plan_params)
  
    if @plan.save
      flash[:notice] = "Successfully updated new plan"
      redirect_to plan_path(@plan)
    else
      flash[:notice] = "Error in updating new plan"
      render :action => 'new'
    end
  end

  def destroy
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  
    @plan = Plan.find(plan_id)
  
    if @plan.destroy
      flash[:notice] = "Successfully destroyed new plan"
      redirect_to user_path(@user)
    else
      flash[:notice] = "Error in destroyed new plan"
      render :action => 'new'
    end
  end

  private
    def plan_params
      params.require(:plan).permit(:title, :description, :meals_attributes => [:id, :title, :description, :options_attributes => [:id, :title, :description, :foods_attributes => [:id, :title, :description, :calories, :protien, :fat, :transfat, :monofat, :polyfat, :carbs, :suger, :fiber, :_destroy]]])
    end

    def plan_id
      params.require(:id)
    end


end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for @plan do |f| %>

  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/><br/>

  <%= f.label :description %><br/>
  <%= f.text_field :description %><br/><br/>

  <%= f.fields_for :meals do |builder | %>
    <%= render 'meal_fields', :f => builder %>
  <% end %>

  <%= f.submit %>

<% end %>

app/views/plans/_meal_fields.html.erb
<%= f.label :title, "Meal Title" %><br/>
<%= f.text_field :title %><br/><br/>

<%= f.label :description, "Meal Description" %><br/>
<%= f.text_field :description %><br/><br/>

<%= f.fields_for :options do |builder | %>
  <%= render 'option_fields', :f => builder %>
<% end %>

app/views/plans/_meals_fields.html.erb
<%= f.label :title, "Meal Title" %><br/>
<%= f.text_field :title %><br/><br/>

<%= f.label :description, "Meal Description" %><br/>
<%= f.text_field :description %><br/><br/>

<%= f.fields_for :options do |builder | %>
  <%= render 'options_fields', :f => builder %>
<% end %>

app/views/plans/_option_fields.html.erb
<%= f.label :title, "Options Title" %><br/>
<%= f.text_field :title %><br/><br/>

<%= f.label :description, "Options Description" %><br/>
<%= f.text_field :description %><br/><br/>

<%= f.fields_for :foods do |builder | %>
  <%= render 'food_fields', :f => builder %>
<% end %>

<p><%= link_to_add_fields "Add Foods", f, :foods %></p>

app/views/plans/_options_fields.html.erb
<%= f.label :title, "Options Title" %><br/>
<%= f.text_field :title %><br/><br/>

<%= f.label :description, "Options Description" %><br/>
<%= f.text_field :description %><br/><br/>

<%= f.fields_for :options do |builder | %>
  <%= render 'foods_fields', :f => builder %>
<% end %>

app/views/plans/edit.html.erb
<h1>Edit Plan</h1>

<%= render partial: 'form' %>

app/views/plans/index.html.erb
<h1>List meal plans for current_user here</h1>
<%= link_to "Create New Plan", new_plan_path, :method => :get %>
<p>One of these plans needs to be capable of beeing set as primary</p>

<% @user.plans.each do |p| %>
  <div class="plan">
  <h1><%= p.title %></h1><p><%= p.description %></p>
  <%= link_to "View", plan_path(p), :method => :get %> |
  <%= link_to "Edit", edit_plan_path(p), :method => :get %> |
  <%= link_to "Delete", plan_path(p), :method => :delete %><br/><br/>
  <% p.meals.each do |m| %>
    <div class="meal">
    <br/><%= link_to "View", plan_meal_path(p, m), :method => :get %> |
    <%= link_to "Edit", edit_plan_meal_path(p, m), :method => :get %> |
    <%= m.title %><br/><br/>
    <% m.options.each do |o| %>
      <div class="option">
      <%= link_to "View", plan_meal_option_path(p, m, o), :method => :get %> |
      <%= link_to "Edit", edit_plan_meal_option_path(p, m, o), :method => :get %><br/>
      <%= o.title %>: 
      <br/><%= o.description %><br/><br/>
      <% count = 1 %>
      <% o.foods.each do |f| %>
        <%= count %> - 
        <%= link_to "View", plan_meal_option_food_path(p, m, o, f), :method => :get %> |
        <%= link_to "Edit", edit_plan_meal_option_food_path(p, m, o, f), :method => :get %> |
        <%= link_to "Delete", plan_meal_option_food_path(p, m, o, f), :method => :delete %>
        <%= f.title %>: <%= f.description %><br/>
        <% count += 1 %>
        <br/>
      <% end %>
      <%= link_to "Add Food", new_plan_meal_option_food_path(p, m, o), :method => :get %>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>
<% end %>

app/views/plans/new.html.erb
<h1>Create new plan here using _form.html.erb</h1>

<%= render partial: 'form' %>

app/views/plans/show.html.erb
<h1>This page shows one plan</h1>

<div class="plan">
<h1><%= @plan.title %></h1><p><%= @plan.description %></p>
<%= link_to "Edit", edit_plan_path(@plan), :method => :get %> |
<%= link_to "Delete", plan_path(@plan), :method => :delete %><br/><br/>
<% @plan.meals.each do |m| %>
  <div class="meal">
  <%= link_to "View", plan_meal_path(@plan, m), :method => :get %> |
  <%= link_to "Edit", edit_plan_meal_path(@plan, m), :method => :get %><br/>
  <% m.options.each do |o| %>
    <div class="option">
    <%= link_to "View", plan_meal_option_path(@plan, m, o), :method => :get %> |
    <%= link_to "Edit", edit_plan_meal_option_path(@plan, m, o), :method => :get %><br/>
    <%= o.title %>: 
    <br/><%= o.description %><br/><br/>
    <% count = 1 %>
    <% o.foods.each do |f| %>
      <%= count %> - 
      <%= link_to "View", plan_meal_option_food_path(@plan, m, o, f), :method => :get %> |
      <%= link_to "Edit", edit_plan_meal_option_food_path(@plan, m, o, f), :method => :get %> |
      <%= link_to "Delete", plan_meal_option_food_path(@plan, m, o, f), :method => :delete %>
      <%= f.title %>: <%= f.description %><br/>
      <br/>
      <% count += 1 %>
    <% end %>
    <%= link_to "Add Food", new_plan_meal_option_food_path(@plan, m, o), :method => :get %>
    </div>
  <% end %>
  </div>
<% end %>
</div>